name: kaif_web
description: Kaif Web
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: any
  less_dart: ">=2.3.8 <3.0.0"
dev_dependencies:
  webdev: ^2.7.1
  build_runner: ^1.11.1
  build_web_compilers: ^2.16.3
