---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-nginx"
  labels:
    {{- include "kaif-web.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

  kaif_www.conf: |
    server {
       listen 80;
       server_name www.kaif.io;
       return 301 https://kaif.io$request_uri;
    }

  kaif_80.conf: |
    proxy_cache_path /var/cache/nginx/kaif_web
                     levels=1:2
                     keys_zone=kaif_web:10m
                     max_size=512m
                     inactive=30d
                     use_temp_path=off;

    ## set real ip from x-forwarded-for client ip from ALB
    ## this required --with-http_realip_module
    ## see https://serverfault.com/questions/896130/possible-to-log-x-forwarded-for-to-nginx-error-log
    ## note that the settings apply to global nginx
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  192.168.0.0/16;
    real_ip_header    X-Forwarded-For;

    server {
      listen 80;
      server_name {{ .Values.kaif.siteServerName }};

      #force https
      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }

      ## security settings
      add_header Strict-Transport-Security "max-age=31536000";
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-Content-Type-Options nosniff;

      gzip on;
      gunzip on;
      gzip_vary on;
      gzip_min_length 10240;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types text/plain text/css text/xml application/javascript text/javascript
                 application/x-javascript application/xml application/json
                 font/ttf font/otf image/svg+xml;
      gzip_disable "msie6";

      ### 1. disable nginx default connection close and overwrite host
      ### 2. preserve IP address
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      proxy_http_version 1.1;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      ### proxy cache require buffering set to on
      proxy_buffering on;

      add_header X-Cache-Status $upstream_cache_status;

      # special ^~ symbol make matching image higher than regex
      location ~* ^.+\.(jpg|jpeg|gif|css|png|js|ico|svg)$ {
        proxy_pass http://localhost:5980;
        access_log off;
      }
      location / {
        proxy_pass http://localhost:5980;
      }
      location /actuator/prometheus {
        return 403;
      }
      if ($http_user_agent ~* "(YisouSpider|EasouSpider|EtaoSpider)") {
        return 403;
      }
      deny 42.120.160.68;
      deny 42.120.161.68;
      allow all;
    }

