apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaif-web.fullname" . }}
  labels:
  {{- include "kaif-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5980
      protocol: TCP
      name: spring
      targetPort: 5980
  selector:
  {{- include "kaif-web.selectorLabels" . | nindent 4 }}
