---
image:
  tag: '13.1.0-debian-10-r67'

service:
  type: NodePort
  nodePort: 30598

initdbScripts:
  recreate_db.sql: |
    DROP DATABASE if exists kaif;
    DROP ROLE if exists kaif;
    CREATE ROLE kaif LOGIN PASSWORD 'changeme' NOINHERIT VALID UNTIL 'infinity';
    CREATE DATABASE kaif WITH ENCODING='UTF8' OWNER=kaif TEMPLATE=template1;
    \c kaif
    ALTER SCHEMA public OWNER TO kaif;

  recreate_db_ci.sql: |
    DROP DATABASE if exists ci_kaif;
    DROP ROLE if exists ci_kaif;
    CREATE ROLE ci_kaif LOGIN PASSWORD 'changeme' NOINHERIT VALID UNTIL 'infinity';
    CREATE DATABASE ci_kaif  WITH ENCODING='UTF8' OWNER=ci_kaif TEMPLATE=template1;
    \c ci_kaif
    ALTER SCHEMA public OWNER TO ci_kaif;

postgresqlConfiguration: {
  "listenAddresses": "'*'"
}

## below is local specific
persistence:
  enabled: true
  existingClaim: kaif-db-postgresq-pvc
  #size: 8Gi

volumePermissions:
  enabled: true

## @formatter:off
extraDeploy:
  - kind: PersistentVolume
    apiVersion: v1
    metadata:
      name: kaif-db-postgresq-pv
      labels:
        app: kaif-db
    spec:
      storageClassName: manual
      capacity:
        storage: 8Gi
      accessModes:
        - ReadWriteMany
      hostPath:
        path: "/volume/pg-data"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: kaif-db-postgresq-pvc
      labels:
        app: kaif-db
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 8Gi
      selector:
        matchLabels:
          app: kaif-db
