---
image:
  tag: '13.1.0-debian-10-r67'

initdbScripts:
  recreate_db.sql: |
    DROP DATABASE if exists kaif;
    DROP ROLE if exists kaif;
    CREATE ROLE kaif LOGIN PASSWORD 'changeme' NOINHERIT VALID UNTIL 'infinity';
    CREATE DATABASE kaif WITH ENCODING='UTF8' OWNER=kaif TEMPLATE=template1;
    \c kaif
    ALTER SCHEMA public OWNER TO kaif;

  recreate_db_ci.sql: |
    DROP DATABASE if exists ci_kaif;
    DROP ROLE if exists ci_kaif;
    CREATE ROLE ci_kaif LOGIN PASSWORD 'changeme' NOINHERIT VALID UNTIL 'infinity';
    CREATE DATABASE ci_kaif  WITH ENCODING='UTF8' OWNER=ci_kaif TEMPLATE=template1;
    \c ci_kaif
    ALTER SCHEMA public OWNER TO ci_kaif;

postgresqlConfiguration: {
  "listenAddresses": "'*'"
}

## below is local specific
persistence:
  enabled: true
  size: 8Gi

service:
  type: NodePort
  nodePort: 30598