# Default values for kaif-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

initialDelaySeconds: 10

kaif:
  ## spring active profile, ex: 'stage,th,stage-th' 'prod,vn,prod-vn'
  springProfile:
  ## jvm extra config, such as '-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=85.0'
  javaOptions: '-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=85.0'
  siteServerName: kaif.io
  gracefulShutdownWait: 10s

springImage:
  repository: k3d-kaif-registry.localhost:5111/kaif/kaif-web
  tag: latest
  pullPolicy: Always

springResources: { }
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nginxResources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

ingress:
  enabled: false
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: [ ]
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }
