## web server
server:
  port: 5980


## freemarker
spring.freemarker:
  cache: true
  settings:
    show_error_tips: false


## spring mvc resources
# cache one month for css, js, favicon.ico...etc
spring:
  resources:
    chain:
      cache: true
    cache:
      cachecontrol:
        max-age: 30d
        cache-public: true

## actuator
management:
  endpoints:
    enabled-by-default: false


## database
spring.datasource:
  initialization-mode: never
  url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost:5432}/kaif
  username: kaif
  password: ${POSTGRES_PASSWORD}
  schema:
  data:

## jmx


## messages


## mail
spring.mail.host: ${SMTP_ADDRESS:localhost}

mail.aws-sender-address: noreply@kaif.io
mail.aws-secret-key: ${MAIL_AWS_SECRET_KEY}
mail.aws-access-key: ${MAIL_AWS_ACCESS_KEY}

## model
account:
  mac: ${ACCOUNT_MAC}
  key: ${ACCOUNT_KEY}


## oauth, see OauthSecret.java
oauth:
  mac: ${OAUTH_MAC}
  key: ${OAUTH_KEY}

## flake node id, every web server should use it's own unique node id
flake.node-id: ${FLAKE_NODE_ID}


## logback
logging.config: classpath:logback-prod.xml


